MIS/2-MIS/PIS/EDR/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'login',  to: 'sessions#new',     as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'rooms',  to: 'rooms#index'
  get 'active', to: 'session#active', as: 'active'
  get 'timeout', to: 'session#timeout', as: 'timeout'

  resources :failures
  resources :transfers
  resources :devices
  resources :users
  resources :schoolrooms
  resources :offices
  resources :employees
  resources :departments
  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '*path', to: 'welcome#index' # TODO: 404 Not Found
end

MIS/2-MIS/PIS/EDR/app/models/transfer.rb
class Transfer < ApplicationRecord
  validate :from_and_to_must_be_different
  belongs_to :device
  belongs_to :author,       class_name: :Employee, foreign_key: :author_id
  belongs_to :approved,     class_name: :Employee, foreign_key: :approved_id, optional: true
  belongs_to :from,         class_name: :Room,     foreign_key: :from_id
  belongs_to :to,           class_name: :Room,     foreign_key: :to_id
  validates  :requested_at, presence: true
  validates  :reason,       presence: true

  def from_and_to_must_be_different
    if (from == to)
      errors.add(:to, "to cannot equal from")
    end
  end

  def finished?
    if (done_at != nil) or (active == false)
      true
    else
      false
    end
  end

  def self.all_not_finished
    self.all.select{|s| !s.finished?}  
  end

  def self.all_active
    self.where(active: true)
  end

end

MIS/2-MIS/PIS/EDR/app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :authorize
  before_action :set_transfer, only: [:show, :edit, :update, :destroy]

  # GET /transfers
  # GET /transfers.json
  def index
    @transfers = TransferDecorator.decorate_collection(Transfer.all_active)
  end

  # GET /transfers/1
  # GET /transfers/1.json
  def show
    access(:read)
    @transfer = @transfer.decorate
  end

  # GET /transfers/new
  def new
    access(:create)
    @transfer  = Transfer.new.decorate
    @devices   = Device.all_not_being_transfered
    @employees = Employee.all_active
    @rooms     = Room.all_active
  end

  # GET /transfers/1/edit
  def edit
    access(:update)
    @transfer  = Transfer.find(params[:id])
    @from      = Room.find(@transfer.from_id).label
    @to        = Room.find(@transfer.to_id).label
    @devices   = Device.all_not_being_transfered
    @employees = Employee.all_active
    @rooms     = Room.all_active
    @device    = Device.find(@transfer.device.id)
    @transfer  = @transfer.decorate
  end

  # POST /transfers
  # POST /transfers.json
  def create
    access(:create)
    checked_params = Hash.new
    checked_params["device"]       = Device.find(transfer_params[:device_id])
    checked_params["author"]       = Employee.find(transfer_params[:author_id])
    checked_params["from"]         = checked_params["device"].room
    checked_params["to"]           = Room.find(transfer_params[:to_id])
    checked_params["reason"]       = transfer_params[:reason]
    checked_params["requested_at"] = transfer_params[:requested_at] || DateTime.now
    checked_params["done_at"]      = transfer_params[:done_at]
    @transfer = Transfer.new(checked_params)
    respond_to do |format|
      if @transfer.save
        format.html { redirect_to @transfer}
        format.json { render :show, status: :created, location: @transfer }
      else
        @devices = Device.all_not_being_transfered
        @employees = Employee.all
        @rooms = Room.all
        format.html { render :new }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transfers/1
  # PATCH/PUT /transfers/1.json
  def update
    access(:update)
    checked_params = Hash.new
    checked_params["device"]       = Transfer.find(params[:id]).device
    checked_params["author"]       = Employee.find(transfer_params[:author_id])
    checked_params["approved"]     = Employee.find(transfer_params[:approved_id])
    checked_params["from"]         = Transfer.find(params[:id]).from
    checked_params["to"]           = Room.find(transfer_params[:to_id])
    checked_params["reason"]       = transfer_params[:reason]
    checked_params["requested_at"] = transfer_params[:requested_at]
    checked_params["done_at"]      = transfer_params[:done_at]

    respond_to do |format|
      if @transfer.update(checked_params)
        if checked_params["done_at"] != nil
          checked_params["device"].update_attribute(:room, checked_params["to"])
        end
        format.html { redirect_to @transfer}
        format.json { render :show, status: :ok, location: @transfer }
      else
        @devices = Device.all_not_being_transfered
        @employees = Employee.all
        @rooms = Room.all
        @device = Device.find(@transfer.device.id)
        format.html { render :edit }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfers/1
  # DELETE /transfers/1.json
  def destroy
    access(:destroy)
    @transfer.update_attribute(:active, false)
    respond_to do |format|
      format.html { redirect_to transfers_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transfer
      @transfer = Transfer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transfer_params
      params.fetch(:transfer, {})
    end

    def access(action)
      authorize!(action, Transfer.new)
    end
end

MIS/2-MIS/PIS/EDR/app/helpers/transfers_helper.rb
module TransfersHelper
end

MIS/2-MIS/PIS/EDR/app/views/transfers/_form.html.erb
<%= bootstrap_form_with(model: transfer, local: true, layout: :horizontal) do |form| %>
  <% if transfer.persisted? %>
    <%= form.text_field :device_id, 
                        value: "ID: " + @device.id.to_s + ", brand: " + @device.brand + ", model: " + @device.model + ", from: " + @device.room.label, 
                        control_col: "col-sm-9", 
                        :disabled => true %>
  <% else %>
    <%= form.select :device_id, 
                    @devices.collect{|d|["ID: " + d.id.to_s + ", brand: " + d.brand + ", model: " + d.model + ", from: " + d.room.label, d.id]}, 
                    {class: "dropdown-menu", control_col: "col-sm-9", label: "Device *"}, 
                    :required => true%>
  <% end %>
  <%= form.select :to_id, 
                  @rooms.collect{|r|[r.label, r.id]}, 
                  {class: "dropdown-menu", control_col: "col-sm-9", label: "To *"}, 
                  :required => true %>
  <%= form.select :author_id, 
                  @employees.collect{|e|["ID: " + e.id.to_s + ", " + e.name + " " + e.surname, e.id]}, 
                  {class: "dropdown-menu", control_col: "col-sm-9", label: "Author *"}, 
                  :required => true %>
  <% if (current_user.material_coordinator? or current_user.administrator?) and transfer.persisted?%>
    <%= form.select :approved_id, 
                    @employees.collect{|e|["ID: " + e.id.to_s + ", " + e.name + " " + e.surname, e.id]}, 
                    {class: "dropdown-menu", control_col: "col-sm-9"}%>
  <% end %>
  <%= form.text_field :reason, control_col: "col-sm-9" %>
  <%= form.datetime_local_field :requested_at, control_col: "col-sm-9", value: @transfer.request_date %>
  <% if can? :update, Transfer %>
    <%= form.datetime_local_field :done_at, control_col: "col-sm-9", value: @transfer.done_date %>
  <% end %>


  <div class="form-group">
    <label class="col-md-4 control-label" for="submit"></label>
    <div class="col-md-8">
      <%= form.submit "Submit", class: "btn btn-dark"%>
      <%= link_to 'Back', transfers_path, {:style => 'color: #FFFFFF', :class => "btn btn-dark"} %>
    </div>
  </div>
<% end %>

MIS/2-MIS/PIS/EDR/app/views/transfers/edit.html.erb
<div align="center">
  <div style="padding-top: 20px; max-width:1000px">
    <h1>Editing Transfer</h1>
    <%= render 'form', transfer: @transfer %>
  </div>
</div>

MIS/2-MIS/PIS/EDR/app/views/transfers/index.html.erb
<p id="notice"><%= notice %></p>

<div class="index" align="center">

    <h1>Transfers</h1>

    <table class="table" style="width:80%; max-width:2500px">
      <thead class="thead-dark">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Device</th>
          <th scope="col">From</th>
          <th scope="col">To</th>
          <th scope="col">Finished</th>
          <th></th>
          <% if can? :update, Transfer %>
            <th></th>
          <% end %>
          <% if can? :destroy, Transfer %>
            <th></th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @transfers.each do |transfer| %>
          <tr>
            <td><%= transfer.id%></td>
            <td><%= transfer.device.brand%> <%= transfer.device.model%></td>
            <td><%= transfer.from.label%></td>
            <td><%= transfer.to.label%></td>
            <td><%= transfer.finished_str %></td>
            <td><%= link_to 'Show', transfer %></td>
            <% if can? :update, Transfer %>
              <td><%= link_to 'Edit', edit_transfer_path(transfer) %></td>
            <% end %>
            <% if can? :destroy, Transfer %>
              <td><%= link_to 'Destroy', transfer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <% if can? :create, Transfer %>
      <div class="btn btn-dark">
          <%= link_to 'New Transfer', new_transfer_path, {:style => 'color: #FFFFFF', :class => "btn"} %>
      </div>
    <% end %>
    <div class="btn btn-dark">
        <%= link_to 'Back', root_path, {:style => 'color: #FFFFFF', :class => "btn"} %>
    </div>
<div>

MIS/2-MIS/PIS/EDR/app/views/transfers/new.html.erb
<div align="center">
  <div style="padding-top: 20px; max-width:1000px">
    <h1>New Transfer</h1>
    <%= render 'form', transfer: @transfer %>
  </div>
</div>

MIS/2-MIS/PIS/EDR/app/views/transfers/show.html.erb
<p id="notice"><%= notice %></p>

<div align="center">
  <h1>Transfer ID: <%= @transfer.id%></h1>

  <div style="max-width:1000px">
    <table class="table table-bordered">
      <thead class="thead-dark">
        <tr>
          <th style="width: 50%"></th>
          <th style="width: 50%"></th>
        </tr>
      </thead>
      <tbody>
        <tr> 
          <td><b>Device</b></td> 
          <td><%=@transfer.device.brand%> <%=@transfer.device.model%></td> 
        </tr>
        <tr> 
          <td><b>From</b></td> 
          <td><%=@transfer.from.label%></td> 
        </tr>
        <tr> 
          <td><b>To</b></td> 
          <td><%=@transfer.to.label%></td> 
        </tr>
        <tr> 
          <td><b>Author</b></td> 
          <td><%=@transfer.author.name%> <%=@transfer.author.surname%></td> 
        </tr>
				<tr>
					<td><b>Approved by</b></td> 
					<%if @transfer.approved != nil %>
						<td><%=@transfer.approved.name%> <%=@transfer.approved.surname%></td> 
					<% end %>
        </tr>
        <tr> 
          <td><b>Reason</b></td> 
          <td><%=@transfer.reason%></td> 
        </tr>
        <tr> 
          <td><b>Requested at</b></td> 
          <td><%=@transfer.requested_at%></td> 
        </tr>
        <tr> 
          <td><b>Done at</b></td> 
          <td><%=@transfer.done_at%></td> 
        </tr>
        <tr> 
          <td><b>Created at</b></td> 
          <td><%=@transfer.created_at%></td> 
        </tr>
        <tr> 
          <td><b>Updated at</b></td> 
          <td><%=@transfer.updated_at%></td> 
        </tr>
        <tr> 
          <td><b>Finished</b></td> 
          <td><%= @transfer.finished_str %></td> 
        </tr>
      </tbody>
    </table>
  </div>

  <%if can? :update, Transfer %>
    <div class="btn btn-dark">
        <%= link_to 'Edit', edit_transfer_path(@transfer), {:style => 'color: #FFFFFF', :class => "btn"} %>
    </div>
  <% end %>
  <div class="btn btn-dark">
      <%= link_to 'Back', transfers_path, {:style => 'color: #FFFFFF', :class => "btn"} %>
  </div>
</div>