MIS/2-MIS/PIS/EDR/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'login',  to: 'sessions#new',     as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'rooms',  to: 'rooms#index'
  get 'active', to: 'session#active', as: 'active'
  get 'timeout', to: 'session#timeout', as: 'timeout'

  resources :failures
  resources :transfers
  resources :devices
  resources :users
  resources :schoolrooms
  resources :offices
  resources :employees
  resources :departments
  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '*path', to: 'welcome#index' # TODO: 404 Not Found
end

MIS/2-MIS/PIS/EDR/app/models/failure.rb
class Failure < ApplicationRecord
  belongs_to :device
  belongs_to :technician,   class_name: :Employee, foreign_key: :technician_id, optional: true
  belongs_to :announcer,    class_name: :Employee, foreign_key: :announcer_id
  validates  :announced_at, presence: true
  validates  :description,  presence: true

  def self.all_active
    self.where(active: true)
  end
end

MIS/2-MIS/PIS/EDR/app/controllers/failures_controller.rb
class FailuresController < ApplicationController
  before_action :authorize
  before_action :set_failure

  FAILURE_PROPERTIES = {
    description:  nil,
    report:       nil,
    announced_at: Time.now,
    solved:       false
  }

  # GET /failures
  # GET /failures.json
  def index
    @failures = FailureDecorator.decorate_collection(Failure.all_active)
  end

  # GET /failures/1
  # GET /failures/1.json
  def show
    access(:read)
    @failure = @failure.decorate
  end

  # GET /failures/new
  def new
    access(:create)
    @failure = Failure.new.decorate
  end

  # GET /failures/1/edit
  def edit
    access(:update)
  end

  # POST /failures
  # POST /failures.json
  def create
    access(:create)
    checked_params = check_params(FAILURE_PROPERTIES)
    checked_params["device"] = Device.find(failure_params["device_id"])
    checked_params["announcer"] = Employee.find(failure_params["announcer_id"])
    @failure = Failure.new(checked_params)
    respond_to do |format|
      if @failure.save
        format.html { redirect_to @failure}
        format.json { render :show, status: :created, location: @failure }
      else
        format.html { render :new }
        format.json { render json: @failure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /failures/1
  # PATCH/PUT /failures/1.json
  def update
    access(:update)
    checked_params = check_params(FAILURE_PROPERTIES)
    checked_params["device"] = Device.find(failure_params["device_id"])
    checked_params["announcer"] = Employee.find(failure_params["announcer_id"])
    if failure_params["technician_id"]
      checked_params["technician"] = Employee.find(failure_params["technician_id"])
    end

    respond_to do |format|
      if @failure.update(checked_params)
        format.html { redirect_to @failure}
        format.json { render :show, status: :ok, location: @failure }
      else
        format.html { render :edit }
        format.json { render json: @failure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /failures/1
  # DELETE /failures/1.json
  def destroy
    access(:destroy)
    @failure.update_attribute(:active, false)
    respond_to do |format|
      format.html { redirect_to failures_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_failure
      @failure     = Failure.find(params[:id]) if params[:id]
      @devices     = Device.all_active
      @employees   = Employee.all_active
      @technicians = Employee.all_technicians
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def failure_params
      params.fetch(:failure, {})
    end

    def check_params(params)
      checked = {}
      params.each do |k, v|
        checked[k] = failure_params[k].blank? ? v : failure_params[k]
      end
      checked
    end

    def access(action)
      authorize!(action, Failure.new)
    end
end

MIS/2-MIS/PIS/EDR/app/helpers/failures_helper.rb
module FailuresHelper
  def technicians_dropdown(list, default)
    options_from_collection_for_select(list, 'id', 'fullname_with_bday', default)
  end

  def announcers_dropdown(list, default)
    options_from_collection_for_select(list, 'id', 'fullname_with_bday', default)
  end

  def devices_dropdown(list, default)
    options_from_collection_for_select(list, 'id', 'fullname', default)
  end
end

MIS/2-MIS/PIS/EDR/app/views/failures/_form.html.erb
<%= bootstrap_form_with(model: failure, local: true, layout: :horizontal) do |form| %>
  <%= form.select(:device_id, devices_dropdown(@devices, @failure.device), field_params(nil, true, 'Device *'), form_class) %>
  <%= form.select(:announcer_id, announcers_dropdown(@employees, @failure.announcer), field_params(nil, true, 'Announcer *'), form_class) %>
  <%= form.text_field :description, field_params %>
  <% if (can? :update, Failure) and @failure.persisted? %>
    <%= form.select(:technician_id, technicians_dropdown(@technicians, @failure.technician), field_params(nil, true, 'Technician *'), form_class) %>
  <% end %>
  <%= form.text_field :report, field_params %>
  <%= form.datetime_local_field :announced_at, field_params.merge(value: @failure.announced_at) %>
  <% if (can? :update, Failure) and @failure.persisted? %>
  	<%= form.check_box :solved, field_params, checked_value = "true", unchecked_value = "false" %>
  <% end %>

  <div class="form-group">
    <label class="col-md-4 control-label" for="submit"></label>
    <div class="col-md-8">
      <%= form.submit "Submit", class: "btn btn-dark"%>
      <%= link_to 'Back', failures_path, {:style => 'color: #FFFFFF', :class => "btn btn-dark"} %>
    </div>
  </div>
<% end %>

MIS/2-MIS/PIS/EDR/app/views/failures/edit.html.erb
<div align="center">
  <div style="padding-top: 20px; max-width:1000px">
    <h1>Editing Failure</h1>
    <%= render 'form', failure: @failure %>
  </div>
</div>

MIS/2-MIS/PIS/EDR/app/views/failures/index.html.erb
<p id="notice"><%= notice %></p>

<div class="index" align="center">

    <h1>Failures</h1>

    <table class="table" style="width:80%; max-width:2500px">
      <thead class="thead-dark">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Device</th>
          <th scope="col">Announcer</th>
          <th scope="col">Date of announcement</th>
          <th scope="col">Technician</th>
          <th scope="col">Solved</th>
          <th></th>
          <% if can? :update, Failure %>
            <th></th>
          <% end %>
          <% if can? :destroy, Failure %>
            <th></th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @failures.each do |failure| %>
          <tr>
            <td><%= failure.id%></td>
            <td><%= failure.device.brand%> <%= failure.device.model%></td>
            <td><%= failure.announcer.name%> <%= failure.announcer.surname%></td>
						<td><%= failure.created_at%></td>
						<td>
							<% if failure.technician != nil %>
								<%= failure.technician.name%> <%= failure.technician.surname%>
							<% end %>
						</td>
						<td><%= failure.solved_str %></td>
            <td><%= link_to 'Show', failure %></td>
            <% if can? :update, Failure %>
              <td><%= link_to 'Edit', edit_failure_path(failure) %></td>
            <% end %>
            <% if can? :destroy, Failure %>
              <td><%= link_to 'Destroy', failure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <% if can? :create, Failure %>
      <div class="btn btn-dark">
          <%= link_to 'New Failure', new_failure_path, {:style => 'color: #FFFFFF', :class => "btn"} %>
      </div>
    <% end %>
    <div class="btn btn-dark">
        <%= link_to 'Back', root_path, {:style => 'color: #FFFFFF', :class => "btn"} %>
    </div>
<div>

MIS/2-MIS/PIS/EDR/app/views/failures/new.html.erb
<div align="center">
  <div style="padding-top: 20px; max-width:1000px">
    <h1>New Failure</h1>
    <%= render 'form', failure: @failure %>
  </div>
</div>

MIS/2-MIS/PIS/EDR/app/views/failures/show.html.erb
<p id="notice"><%= notice %></p>

<div align="center">
  <h1>Failure ID: <%= @failure.id%></h1>

  <div style="max-width:1000px">
    <table class="table table-bordered">
      <thead class="thead-dark">
        <tr>
          <th style="width: 50%"></th>
          <th style="width: 50%"></th>
        </tr>
      </thead>
      <tbody>
        <tr> 
          <td><b>Device</b></td> 
          <td><%=@failure.device_name %></td> 
        </tr>
        <tr> 
          <td><b>Announcer</b></td> 
          <td><%=@failure.announcer_name %></td> 
        </tr>
        <tr> 
          <td><b>Technician</b></td> 
          <td><%=@failure.technician_name %></td> 
        </tr>
        <tr> 
          <td><b>Description</b></td> 
          <td><%=@failure.description %></td> 
        </tr>
        <tr> 
          <td><b>Report</b></td> 
          <td><%=@failure.report %></td> 
        </tr>
        <tr> 
          <td><b>Announced</b></td> 
          <td><%=@failure.announced_at %></td> 
        </tr>
        <tr> 
          <td><b>Solved</b></td> 
          <td><%=@failure.solved_str %></td> 
        </tr>
        <tr> 
          <td><b>Updated</b></td> 
          <td><%=@failure.updated_at %></td> 
        </tr>
      </tbody>
    </table>
  </div>

  <% if can? :update, Failure %>
    <div class="btn btn-dark">
        <%= link_to 'Edit', edit_failure_path(@failure), {:style => 'color: #FFFFFF', :class => "btn"} %>
    </div>
  <% end %>
  <div class="btn btn-dark">
      <%= link_to 'Back', failures_path, {:style => 'color: #FFFFFF', :class => "btn"} %>
  </div>
</div>