MIS/2-MIS/PIS/EDR/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'login',  to: 'sessions#new',     as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'rooms',  to: 'rooms#index'
  get 'active', to: 'session#active', as: 'active'
  get 'timeout', to: 'session#timeout', as: 'timeout'

  resources :failures
  resources :transfers
  resources :devices
  resources :users
  resources :schoolrooms
  resources :offices
  resources :employees
  resources :departments
  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '*path', to: 'welcome#index' # TODO: 404 Not Found
end

MIS/2-MIS/PIS/EDR/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MIS/2-MIS/PIS/EDR/app/models/department.rb
class Department < ApplicationRecord
  has_many  :rooms,    dependent: :destroy
  validates :name,     presence: true
  validates :shortcut, presence: true
  validates :shortcut, uniqueness: true

  def self.all_active
    self.where(active: true)
  end
end

MIS/2-MIS/PIS/EDR/app/models/device.rb
class Device < ApplicationRecord
  belongs_to :room
  belongs_to :employee
  validates  :brand, presence: true
  validates  :model, presence: true
  validates  :price, presence: true

  def being_transfered?
    Transfer.all_not_finished.each do |nf|
      if (nf.device == self)
        return true
      end  
    end
    return false
  end

  def self.all_active
    self.where(active: true)
  end

  def self.all_not_being_transfered
    self.all_active.select { |s| !s.being_transfered? }
  end

  def fullname
    "#{brand} #{model}"
  end
end

MIS/2-MIS/PIS/EDR/app/models/employee.rb
class Employee < ApplicationRecord
  validate :email_must_be_unique
  belongs_to :office
  validates  :name,       presence: true
  validates  :surname,    presence: true
  validates  :birth_date, presence: true
  validates  :email,      presence: true
  validates  :email, uniqueness: true
  before_destroy :remove_user

  def self.all_active
    self.where(active: true)
  end

  def remove_user
    User.where(employee_id: id) do |e|
      e.destroy
    end
  end

  def user
    User.where(employee_id: id).first
  end

  def user?
    !user.nil?
  end

  def fullname
    "#{name} #{surname} (#{birth_date.strftime('%F')})"
  end

  def fullname_with_bday
    "#{fullname} (#{birth_date.strftime('%F')})"
  end

  def email_must_be_unique
    Employee.all.each do |s|
      if (s.email == email) and (s != self)
        errors.add(:email, "email must be unique")
      end
    end
  end

  def self.all_technicians
    technicians = Array.new
    User.all.each do |u|
      if (u.right.level == 1)
        technicians.push(u.employee)
      end
    end
    return technicians
  end

  def self.all_without_user_account
    emp_with_acc = Array.new
    Employee.all.each do |e|
      User.all.each do |u|
        if u.employee == e
          emp_with_acc.push(e)  
        end
      end
    end
    Employee.all - emp_with_acc
  end
end

MIS/2-MIS/PIS/EDR/app/models/failure.rb
class Failure < ApplicationRecord
  belongs_to :device
  belongs_to :technician,   class_name: :Employee, foreign_key: :technician_id, optional: true
  belongs_to :announcer,    class_name: :Employee, foreign_key: :announcer_id
  validates  :announced_at, presence: true
  validates  :description,  presence: true

  def self.all_active
    self.where(active: true)
  end
end

MIS/2-MIS/PIS/EDR/app/models/office.rb
class Office < RoomBase
  before_destroy :update_employees

  def update_employees
    Employee.where(office_id: id).each do |e|
      e.update_attribute(:office_id, nil)
    end
  end

  def room_label
    room.label if room
  end
end

MIS/2-MIS/PIS/EDR/app/models/right.rb
class Right < ApplicationRecord
  has_many  :users, dependent: :destroy
  validates :name,  presence:  true
  validates :level, presence:  true

  def self.admin
    self.find_by_level(0)
  end

  def self.technician
    self.find_by_level(1)
  end

  def self.personel_clerk
    self.find_by_level(2)
  end

  def self.material_coordinator
    self.find_by_level(3)
  end

  def self.employee
    self.find_by_level(4)
  end
end

MIS/2-MIS/PIS/EDR/app/models/room.rb
class Room < ApplicationRecord
  belongs_to :department
  has_many   :devices
  validates  :label, presence: true
  validates  :label, uniqueness: true

  def self.all_active
    self.where(active: true)
  end
end

MIS/2-MIS/PIS/EDR/app/models/room_base.rb
class RoomBase < ApplicationRecord
  self.abstract_class = true
  belongs_to :room

  def departments
    Department.all_active
  end

  def self.all_active
    self.all.select { |x| x.room.active }
  end
end

MIS/2-MIS/PIS/EDR/app/models/schoolroom.rb
class Schoolroom < RoomBase
  def seats_per_row
    rows > 0 ? (seats / rows).to_i : nil
  end
end

MIS/2-MIS/PIS/EDR/app/models/transfer.rb
class Transfer < ApplicationRecord
  validate :from_and_to_must_be_different
  belongs_to :device
  belongs_to :author,       class_name: :Employee, foreign_key: :author_id
  belongs_to :approved,     class_name: :Employee, foreign_key: :approved_id, optional: true
  belongs_to :from,         class_name: :Room,     foreign_key: :from_id
  belongs_to :to,           class_name: :Room,     foreign_key: :to_id
  validates  :requested_at, presence: true
  validates  :reason,       presence: true

  def from_and_to_must_be_different
    if (from == to)
      errors.add(:to, "to cannot equal from")
    end
  end

  def finished?
    if (done_at != nil) or (active == false)
      true
    else
      false
    end
  end

  def self.all_not_finished
    self.all.select{|s| !s.finished?}  
  end

  def self.all_active
    self.where(active: true)
  end

end

MIS/2-MIS/PIS/EDR/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :employee
  belongs_to :right
  validates  :password, presence: true, length: { in: 8..20 }
  validates  :login, presence: true
  validates  :password_confirmation, presence: true, length: { in: 8..20 }
  validates  :login, uniqueness: true

  def material_coordinator?
    right.level == 3
  end

  def personel_clerk?
    right.level == 2
  end

  def technician?
    right.level == 1
  end

  def administrator?
    right.level == 0
  end

  # AccessGranted required field
  def is_admin
    administrator?
  end

  def self.all_active
    self.where(active: true)
  end
end

MIS/2-MIS/PIS/EDR/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # GET /rooms
  # GET /rooms.json
  def index
    @offices     = OfficeDecorator.decorate_collection(Office.all_active)
    @schoolrooms = SchoolroomDecorator.decorate_collection(Schoolroom.all_active)
  end
end

MIS/2-MIS/PIS/EDR/app/helpers/devices_helper.rb
module DevicesHelper
  def employees_dropdown(list, default)
    options_from_collection_for_select(list, 'id', 'fullname_with_bday', default)
  end

  def rooms_dropdown(list, default)
    options_from_collection_for_select(list, 'id', 'label', default)
  end
end

MIS/2-MIS/PIS/EDR/app/helpers/employees_helper.rb
module EmployeesHelper
  def offices_dropdown(list, default)
    options_from_collection_for_select(list, 'id', 'room_label', default)
  end
end

MIS/2-MIS/PIS/EDR/app/helpers/failures_helper.rb
module FailuresHelper
  def technicians_dropdown(list, default)
    options_from_collection_for_select(list, 'id', 'fullname_with_bday', default)
  end

  def announcers_dropdown(list, default)
    options_from_collection_for_select(list, 'id', 'fullname_with_bday', default)
  end

  def devices_dropdown(list, default)
    options_from_collection_for_select(list, 'id', 'fullname', default)
  end
end

MIS/2-MIS/PIS/EDR/app/helpers/offices_helper.rb
module OfficesHelper
end

MIS/2-MIS/PIS/EDR/app/helpers/rights_helper.rb
module RightsHelper
end

MIS/2-MIS/PIS/EDR/app/helpers/rooms_helper.rb
module RoomsHelper
end

MIS/2-MIS/PIS/EDR/app/helpers/sessions_helper.rb
module SessionsHelper
end

MIS/2-MIS/PIS/EDR/app/helpers/transfers_helper.rb
module TransfersHelper
end

MIS/2-MIS/PIS/EDR/app/helpers/users_helper.rb
module UsersHelper
end

MIS/2-MIS/PIS/EDR/app/helpers/welcome_helper.rb
module WelcomeHelper
end

MIS/2-MIS/PIS/EDR/app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<div class="index" align="center">

    <h1>Offices</h1>

    <table class="table" style="width:80%; max-width:2500px">
      <thead class="thead-dark">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Label</th>
          <th scope="col">Department</th>
          <th></th>
          <% if can? :update, Office %>
            <th></th>
          <% end %>
          <% if can? :destroy, Office %>
            <th></th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @offices.each do |office| %>
          <tr>
            <td><%= office.id%></td>
            <td><%= office.room_label%></td>
            <td><%= office.dpt_shortcut%></td>
            <td><%= link_to 'Show', office %></td>
            <% if can? :update, Office %>
              <td><%= link_to 'Edit', edit_office_path(office) %></td>
            <% end %>
            <% if can? :destroy, Office %>
              <td><%= link_to 'Destroy', office, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <% if can? :create, Office %>
    <div class="btn btn-dark">  
        <%= link_to 'New Office', new_office_path, {:style => 'color: #FFFFFF', :class => "btn"} %>
    </div>
    <% end %>
    <div class="btn btn-dark">  
        <%= link_to 'Back', root_path, {:style => 'color: #FFFFFF', :class => "btn"} %>
    </div>

    <h1 style="margin-top:40px">Schoolrooms</h1>

    <table class="table" style="width:80%; max-width:2500px">
      <thead class="thead-dark">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Label</th>
          <th scope="col">Department</th>
          <th></th>
          <% if can? :update, Schoolroom %>
            <th></th>
          <% end %>
          <% if can? :destroy, Schoolroom %>
            <th></th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @schoolrooms.each do |schoolroom| %>
          <tr>
            <td><%= schoolroom.id%></td>
            <td><%= schoolroom.room_label%></td>
            <td><%= schoolroom.dpt_shortcut%></td>
            <td><%= link_to 'Show', schoolroom %></td>
            <% if can? :update, Schoolroom %>
              <td><%= link_to 'Edit', edit_schoolroom_path(schoolroom) %></td>
            <% end %>
            <% if can? :destroy, Schoolroom %>
              <td><%= link_to 'Destroy', schoolroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <% if can? :create, Schoolroom %>
    <div class="btn btn-dark">
        <%= link_to 'New Schoolroom', new_schoolroom_path, {:style => 'color: #FFFFFF', :class => "btn"} %>
    </div>
    <% end %>
    <div class="btn btn-dark">
        <%= link_to 'Back', root_path, {:style => 'color: #FFFFFF', :class => "btn"} %>
    </div>
<div>